site:
  title: "Antora Documentation Preview"
  url: http://localhost:2020/
  start_page: COMPONENT_NAME::index.adoc
content:
  sources:
  - url: /preview/antora
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: ANTORA_PATH
ui:
  supplemental_files: 
    - path: ./docs/antora/supplemental-ui
    - path: .nojekyll
  bundle:
    url: ANTORA_UI_BUNDLE
    snapshot: false
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  extensions:
  - asciidoctor-kroki
  - '@feelpp/asciidoctor-extensions'
output:
  destinations:
  - provider: fs
    path: /preview/public/serve
    clean: true
