site:
  title: PrePost Processing for Scientific Computing
  url: https://trophime.github.io/CSMI-PrePost/
  start_page: course-prepost::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  supplemental_files: 
    - path: ./docs/antora/supplemental-ui
    - path: .nojekyll
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  extensions:
  - '@feelpp/asciidoctor-extensions'
